logging:
  level:
    ROOT: INFO

server:
  port: ${PORT:8081}
  servlet:
    context-path: /api/product-service

spring:
  profiles:
    active: dev
  application:
    name: 'product-service'
  redis:
    host: localhost
    port: 6379
    password: 12345
    timeout: 1500 # 1,5s
  cache:
    redis:
      key-prefix: 'myCache:'
      use-key-prefix: true
      cache-null-values: false

  datasource:
    url: jdbc:postgresql://localhost:5432/db_01?currentSchema=sale
    username: postgres
    password: 123456

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: 'none'
    open-in-view: false

  liquibase:
    enabled: true
    default-schema: sale
    change-log: classpath:db/liquibase-changelog-master.xml

application:

